2015-02-05 17:08:54,005 DEBUG dataRow number: [5001] aligns with sourcePatientNo: []
2015-02-05 17:08:54,005 ERROR Printing contents of duff Row: [5001] ...
2015-02-05 17:08:54,007 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-02-05 17:08:54,012 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-02-05 17:08:54,012 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-02-05 17:08:54,012 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-02-05 17:08:54,012 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-02-05 17:08:54,013 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-02-05 17:08:54,013 ERROR   Cell: [7] has contents: [unknown]
2015-02-05 17:08:54,013 ERROR   Cell: [8] has contents: [unknown]
2015-02-05 17:08:54,013 ERROR   Cell: [9] has contents: [unknown]
2015-02-05 17:08:54,013 ERROR   Cell: [10] has contents: [unknown]
2015-02-05 17:08:54,013 ERROR Unexpected exception thrown in diagnostics. Will continue!
java.lang.NullPointerException
	at org.brisskit.i2b2.I2B2Project.printDuffRowToLog(I2B2Project.java:1036)
	at org.brisskit.i2b2.I2B2Project.produceFacts(I2B2Project.java:943)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:179)
	at org.brisskit.i2b2.I2B2Project.processSpreadsheet(I2B2Project.java:162)
	at org.brisskit.i2b2.I2B2ProjectTests.testSpreadsheetWithLotsEmptyRows(I2B2ProjectTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

